// <auto-generated />
using System;
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220401204856_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AdmissionDate = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Ginger Tabby",
                            Gender = "Male",
                            Name = "McCavity",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            AdmissionDate = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Sokoke",
                            Gender = "Female",
                            Name = "Grizabella",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            AdmissionDate = new DateTime(2022, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Tuxedo",
                            Gender = "Male",
                            Name = "Mr.Mistopholes",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            AdmissionDate = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Bloodhound",
                            Gender = "Male",
                            Name = "Hubert",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            AdmissionDate = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Terrier",
                            Gender = "Female",
                            Name = "Winky",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            AdmissionDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Weimaraner",
                            Gender = "Female",
                            Name = "Beatrice",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            AdmissionDate = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Syrian",
                            Gender = "Male",
                            Name = "Hamtaro",
                            Type = "Hamster"
                        },
                        new
                        {
                            AnimalId = 8,
                            AdmissionDate = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Roborovski",
                            Gender = "Male",
                            Name = "Boss",
                            Type = "Hamster"
                        },
                        new
                        {
                            AnimalId = 9,
                            AdmissionDate = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Syrian",
                            Gender = "Male",
                            Name = "Howdy",
                            Type = "Hamster"
                        },
                        new
                        {
                            AnimalId = 10,
                            AdmissionDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Mini Satin",
                            Gender = "Male",
                            Name = "Roger",
                            Type = "Rabbit"
                        },
                        new
                        {
                            AnimalId = 11,
                            AdmissionDate = new DateTime(2022, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Netherland Dwarf",
                            Gender = "Male",
                            Name = "Thumper",
                            Type = "Rabbit"
                        },
                        new
                        {
                            AnimalId = 12,
                            AdmissionDate = new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Lilac",
                            Gender = "Male",
                            Name = "Bunnicula",
                            Type = "Rabbit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
